language: objective-c
osx_image: xcode8
podfile: Example/Podfile

script:
- set -o pipefail && xcodebuild test -workspace Example/Optik.xcworkspace -scheme Optik-Example -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' | xcpretty
- pod lib lint
