language: swift
osx_image: xcode7

script:
- set -o pipefail && xcodebuild test -workspace Example/Optik.xcworkspace -scheme Optik-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
